services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    OW\CommunicationBundle\:
        resource: '../../../communication-bundle/*'
        exclude: '../../../communication-bundle/{Builder,Event,Entity,Repository,Tests}'